# Generated by Django 6.1 on 2026-08-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abroad', '0003_remove_students_name_students_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='username',
            new_name='user',
        ),
    ]
