# Generated by Django 6.1 on 2026-08-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad', '0004_rename_username_students_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
