# Generated by Django 6.1 on 2026-08-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad', '0005_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
